apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
        # replace by your key cloack host
        #- KEYCLOAK_HOST
        - keycloak.localhost
  rules:
    # replace by your key cloack host
    #- host: KEYCLOAK_HOST
    - host: keycloak.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080